weechat/scripts

- python/stick_buffer.py
Including changes made in the https://github.com/weechatter/weechat-scripts repo
Mostly https://github.com/weechatter/weechat-scripts/pull/17
Changes made:
- Stop script from truncating localvar lookup to first character of the buffer number
- Clean up destination buffer number logic
- Update copyright (due to @weechatter)
> stick_buffer.py 0.3: fix buffer detection logic

- lua/oldswarner.lua
Without this patch, url could get searched as if they were pattern.
The "plain=true" parameter will fix this.
> [oldswarner] FIX urls are not patterns!

- python/urlbar.py
Undo accidental removal of legacy code: https://github.com/weechat/scripts/commit/f96d74844aec796c924f909d1d43b9b3af4778e4#diff-c0687188b374fa8e50bfd824a408fa6cL225
> urlbar.py 12: fix error on empty prefix (closes #51)

- python/otr.py
IRC nicks are case insensitive. Treat all cases of a nick as equivalent.
> otr.py 1.8.0: fix nick case sensitivity bug

- python/autoauth.py
Currently both auth.rb and autoauth.py use the same command `/auth`, which makes using the scripts at once rather inconvenient.
*Issue occurred for FranX in #weechat.*
There is no inherent reason for autoauth.py to not use `/autoauth` as command to avoid conflicts, so this pull request makes exactly that change. Script major version incremented due to incompatibility.
> autoauth 1.0: rename command /auth to /autoauth

- python/bitlbee_completion.py
@Roger are you ok with this ?
The way attributes are represented in weechat seems to have changed and broken this script.
I noticed the topic didn't match with the expected one : mine is `'Welcome to the control channel. Type \x1a\x01help\x1b\x01 for help information.'` while expected is `'Welcome to the control channel. Type \x02help\x02 for help information.'`
This simply strips any attributes before doing the topic comparison which fixes the problem.
> bitlbee_completion.py 0.2: strip color attributes for topic detection

- python/histsearch.py
Usually input bar's size is set to `1` and with many long inputs this script's output is impossible to see as it just doesn't fit the input bar. The way this PR solves the issue is by adding an additional option allowing the display of only the currently selected historical command instead of the whole list, fitting into the input bar much more likely. It also is more like bash's behavior.
*Feature requested and PR confimed working by TreyHarris in #weechat.*
> histsearch.py 0.3: add option to only display selected command

- python/colorize_nicks.py
Before this change changing the hash algorithm used for random nick colors did not affect colorize_nicks, it just kept using the old colors since it caches them. This patch makes the script repopulate its colors cache when the hash algorithm changes to reflect actual nick colors.
It hooks the moved hash algorithm option in 1.5 so this only makes a difference to anyone on a fresh enough version of WeeChat. An additional hook for the old option could've been added but it's not worth keeping too much backwards compatibility.
> colorize_nicks.py 22: invalidate cached colors on hash algorithm change

- python/noirccolors.py
Closes #98, as discussed on https://github.com/weechat/weechat/issues/745.
> noirccolors.py 0.2: fix wrong example syntax to /buffer set

- python/grep.py
With the default settings, the `get_home` function returns an invalid path such as:
`/home/user//home/user/.weechat/logs`
This is caused by calling `abspath` on a path that starts with a `%h` placeholder which turns the path into an absolute path from the working directory (`/home/user/%h/logs`).
This uses the new `string_eval_path_home` function which does this correctly.
> grep 0.7.7: fix get_home function

- python/weemustfeed.py
Changes:
Add notify_message tag to all prints of feed updates.
Add notify_message and irc_error tags to all prints of RSS feed update
errors.
Inline the MIT license and add revision log.
Version bump.
I have been unsuccessful in my attempts to contact the original author (Bit Shift); their e-mail domain is dead and the name is too generic to deduce their online identity. The script has not changed since its initial inclusion on 2013-10-19. I therefore request that the requirement of contacting the author directly be waived and that I'll be allowed to take over maintenance of weemustfeed.py. I don't intend to introduce significant changes beyond the current version; I may at some point make the weemustfeed buffer open automatically at script load but no plans beyond that.
> weemustfeed.py 0.2.3: tag prints w/ notify_message

- python/autosort.py
Fixes python3 compatibility due to `str` difference between python2/3
> autosort 2.8: fix python3 compatibilty

- python/go.py
An extra fuzzy match check was added to displaying the search results to avoid buffers matched by number from being rendered using fuzzy search display methods which fail in this case due to the number not actually being present in the buffer name.
> go.py 2.3: fix fuzzy search breaking buffer number search display (closes #191)

- python/shortenurl.py
I talked in IRC with someone about this Bug. It seems, that is.gd changed the API call, and there was immediately a fix for this.
> shortenurl.py 0.6.1: fix api call to is.gd

- python/title.py
I sent the author (xt <xt@bash.no>) an email about this change on 7 April 2017 (pasted below), but have not received any response.  This change is simple and straightforward, and keeps existing behaviour by default.
> Thanks for the weechat title.py script, it's great and made it very
> easy to get this info in the terminal title where it belongs!
>
> However, I use buffers.pl rather than the hotlist, so I'm not
> interested in having the hotlist clutter up my terminal title.  Would
> you consider applying the following patch to the script?  It adds an
> option to control whether or not the hotlist is added to the terminal
> title.  It defaults to on (existing behaviour), and the code change is
> very simple and straightforward...
> title.py 0.9: Make hotlist optional

- python/autosort.py
This PR fixes the use of `unicode` in python3 (by making it synonymous to `str`, I kinda wish python3 had done that itself).
> autosort 3.2: Fix python3 compatiblity.

- python/autosort.py
Changelog:
* Fix the /autosort debug command for unicode.
* Update the default rules to work better with Slack.
I updated the defaults since #246 after some more discussion on IRC (couldn't re-open the other PR because I force-pushed to the branch).
> autosort.py 3.3: Fix debug command for unicode buffer names.

- python/automerge.py
There was an error message, `=!= Error: unknown command "/merge" (type /help for help)`, fixed by changing `/merge` to `/buffer merge`, perhaps author had an alias.
> automerge.py 0.2: fix the merge command

- python/mqtt_notify.py
A 'big' update and partial rewrite to this script. I have been running and bugfixing it myself for several weeks, and for about a week in it's current version. It seems pretty stable to me.
I added some variables to customize the hook data field, with defaults that are backwards compatible.
Other changes should not have any impact on the functionality, not breaking client side scripts. I basically only added some keys to the message `json`, but kept everything  that existed as is.
- checks: autopep8 validated
- feature: add variables to customize the data fiels in the
print hooks, default values are backwards compatible
- feature: add messages on connecting/disconnecting to mqtt
- feature: add script unload hook function to clean up the mqtt
connection
- feature: add variable for mqtt …
> mqtt_notify.py: v0.5: major update

- python/bufsave.py
Adding support to bufsave.py for path names containing ~ and other characters supported by python's `os.path.expanduser` function.
mentioning @flashcode for sign-off as the only visible contributor to this plugin on Github.
> bufsave.py 0.4: added support for home path expansion

- python/alternatetz.py
Another one of those "this feels way too trivial" py3ok-fixes: harmonizes whitespace.
Tested on 2.2 with python 2.7.15 and on 2.3-dev with python 3.7.0
> alternatetz.py 0.3: py3k-ok by fixing tabs/spaces.

- python/shortenurl.py
The api.php is depricated. So i changed it according to the
reference: https://is.gd/apishorteningreference.php
This is the current situation:
The change will result in the following situation:
> shortenurl.py 0.6.3: is.gd api call changed

- guile/weechataboo.scm
This PR updates the *weechataboo.scm* script to version 0.1.2, which works with WeeChat relays.
> weechataboo.scm 0.1.2: Fixed relay-usage

- python/fullwidth.py
From the wikipedia article [Halfwidth and fullwidth forms](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms):
> U+FF00 does not correspond to a fullwidth ASCII 20 (space character), since that role is already fulfilled by U+3000 "ideographic space".
(12288 is decimal U+3000)
---
Note: According to the [contributing guidelines](https://github.com/weechat/scripts/blob/master/Contributing.adoc), I have contacted `GermainZ <germanosz@gmail.com>` as of immediately after creating this PR. Hopefully they respond soon :)
Additionally, I checked their github profile page, and they don't seem to have a personal repository for fullwidth.py (it's... not a large script), so keeping code in sync shouldn't be a problem.
> fullwidth.py 0.1.1: Correctly handle fullwidth spaces.

- python/shortenurl.py
It seems that is.gd updated their policy and a 'User-Agent' is needed on requests. I shortly checked that with the following script:
```
import urllib2
string = "http://is.gd/api.php?longurl=https%3A%2F%2Fmedia.ccc.de%2Fv%2Fbiometrie-s8-iris "
req = urllib2.Request(string)
try:
print("without agent:")
res = urllib2.urlopen(req)
ans = res.read()
print(ans)
except Exception, e:
print(e)
opener = urllib2.build_opener()
opener.addheaders = [('User-Agent', 'weechat')]
try:
print("with agent:")
resp = opener.open(string).read()
print(resp)
except Exception, e:
print(e)
```
which results in
```
without agent:
HTTP Error 403: Forbidden
with agent:
https://is.gd/Y3BSrS
```
And updated the plugin accordingly.
> shortenurl.py 0.6.4: add user agent to fix 403 on is.gd

- python/grep_filter.py
The enable and disable commands included newlines in the completion
template. When multiline.pl is loaded, this caused newlines to be shown
in the input bar after completing those commands.
I didn't find any other repo for this script. Since the author hasn't updated the script in three years, and this is such a small change, I didn't contact the author about it.
> grep_filter.py 0.10: Remove newlines from command completion

- python/zncplayback.py
I used futurize to convert the script, tested it worked with both Python 2 and Python 3, and then updated the changelog / version.
> zncplayback.py 0.2.0: make script compatible with Python 3

- python/shortenurl.py
Corrected encoding trouble (with tinyurl ?) showing [ b'http://tinyurl.com/abcdef' ]
Corrected a trouble making show_own not working when user is op, halfop or voice
> shortenurl.py: Correction of small bugs

- python/autosort.py
This PR updates the default rules of `autosort.py` to work with bitlbee, matrix and slack.
> autosort.py 3.7: Make default rules work with bitlbee, matrix and slack.

- python/histsearch.py
In Python3 at least `map` is lazy and doesn't immediately execute the function. This causes histsearch.py never unhooking its `hook_command_run` hooks, which makes WeeChat completely unusable.
> histsearch.py 0.6: fix hook_command_run hooks not being unhooked

- python/autosort.py
Changelog:
* Fix relative sorting on script name in default rules.
* Document a useful property of stable sort algorithms.
> autosort.py 3.8: Fix grouping/sorting on script name in default rules.

- python/grep.py
- use pickle.dumps(s, 0) to force older ascii-compatible pickling protocol
This prevents encoding/decoding to/from utf8 to mess the string up
- cast zip() to a list, as zip does not have length
- cast range() to list, as range cannot reverse()
- open file in utf8 and ignore error just in case
Fixes #404
---------
Replace #372 that has been inactive for ages.
This appears to work for me, but might be missing more - I tried normal grep, count, context, /logs... at least what I'm using is now functional.
Honestly the whole pickling doesn't make sense to me, I'm not sure what the point was, but weechat apparently does unholy things which corrupt the string (doing the same without specifying version 0 of the protocol complains about truncated pickle?!)
I also didn't test in python2, but I …
> grep.py 0.8.3: more python3 compatibility fixes

- python/buffer_dmenu.py
Previously, buffer_dmenu used `str.decode("utf-8")` in several places;
however, this is incompatible with Python 3 and unnecessary since Python
3 uses UTF-8 strings by default. Removing all uses of `.decode("utf-8")`
makes the script Python 3 compatible.
> buffer_dmenu.py 0.1.2: Add Python 3 support

- python/autosort.py
Changelog:
* Remove buffers.pl from recommended settings.
Beucase the `buffers.pl` script has long since been replaced by the `buflist` plugin.
>  autosort.py 3.9: Remove buffers.pl from recommended settings.

- python/confversion.py
The confversion script still used some python2 syntax, however, weechat has moved to python3, so this pull request provides for the syntactic differences between the two versions (as far as I've found them); it works for me with the python3 powered pluginapi.
Please ping me if you spot further issues; even stylistic ones (I'm not that familiar with python).
Best regards,
Simon
> confversion.py 0.3: Adapt to python 3

- python/grep.py
`range` returns a generator in Python 3, and you can't call `.reverse()` on those.
> grep.py: Fix Python 3 issue reversing range

- python/colorize_nicks.py
simple fix: referencing `modifier_data` is no longer correct because it needs version-specific parsing, which was already being done.
I notice there's a couple of other `colorize_nicks.py` PRs - I'm happy to fix this PR if those are merged first!
> colorize_nicks.py 28: fix ignore_tags, broken by weechat 2.9 changes

- python/styurl.py
- Script name: `styurl`
- Version: 1.0
- Requirements: None (uses Python module `re` and the WeeChat Python API)
- Min WeeChat version: Unknown
- Script tags: `url`, `py3`
I created this script because the trigger displayed on the wiki (https://github.com/weechat/weechat/wiki/Triggers) only allows POSIX regex, and some of the regex I was testing was flaky or plain didn't work with ERE. Using Python's regex, I have more options for which regex string I wish to use.
> New script styurl.py: Style URLs using a Python regex

- python/gnome_screensaver_away.py
- Script name: gnome_screensaver_away.py
- Version: 0.2.1
- Requirements: dbus-python
- Min WeeChat version: 0.3.0
@flashcode I haven't marked this as Python 3 compatible yet, as I'm not 100% sure. I tested before and after this change and found a bug (unrelated to this change) where this script being loaded seems to prevent clean `/quit` of weechat. Since I've _only_ got Python 3 at the moment, that's where I've experienced it. I don't know whether it also currently happens with Python 2. I'll try to find some more time to figure it out, but it might take a while to get all the weechat scripting stuff back into my head again!
Since the issue I describe also happens with the existing version, I think it's still reasonable to consider merging this change.
> gnome_screensaver_away.py 0.2.1: Add missing call to infolist_free

- python/go.py
- Script name: go.py
- Version: 2.6
The motivation here is that weechat-matrix uses machine-readable room ids as full names that aren't human friendly. It does offer an option to use human-readable full names, but these are neither unique nor stable, causing trouble with logging. Therefore I figured that the best way to fix this is to optionally use server names in go.py and let weechat-matrix use the unique room ids.
No but I reckon it's all right to open a PR directly since @flashcode is the maintainer of this repo too.
> go.py 2.7: add new option to prefix short names with server names

- python/soju.py
- Script name: soju
- Version: 0.1.0
- Requirements: none
- Min WeeChat version: N/A
- Script tags: bouncer, server
This script provides integration with the [soju](https://soju.im) bouncer. Users can set up a single connection to the bouncer, the plugin will open new connections for each network the bouncer is connected to.
> New script soju.py: soju bouncer integration

- python/soju.py
These messages aren't recognized by WeeChat and display an error in
the server buffer. Eat the messages to suppress the error. Since
commit [1], this will make WeeChat ignore the messages. Before that
commit, WeeChat ignores the hook's return value.
[1]: https://github.com/weechat/weechat/commit/ff8beb1918816ccd1c15954f7f564ab02e9cfb9f
> soju.py 0.1.1: eat BOUNCER messages

- perl/parse_relayed_msg.pl
- Script name: `parse_relayed_msg.pl`
- Version: `1.9.6`
When a relayed message contains both an `@` and `>`, the "message from muninn bot" regex incorrectly parses everything up to the `>` following the `@` as the nickname, instead of the first occurrence of the `>` character.
For example when a bot would relay someone's message `"blub @ foo > test"`, I would see this being output as someone called `"nick> blub @ foo "` sending the message `"test"`.
This is a minimal fix that makes sure that the regex does not match when a `>` precedes the matched `@` symbol.
Fixes #382.
> parse_relayed_msg.pl 1.9.6: fix nick parsing with messages containing @ and >

- perl/chanmon.pl
- Script name: chanmon.pl 
- Version: 2.7
This adds a new configuration for the tags that identify the messages the script should work on. The default value corresponds to the previous behavior.
Full disclosure: My knowledge of perl as a programming language is almost non-existent.
Example: If you are using the weechat-matrix script you might append `matrix_message` to the list of tags to let chanmon monitor matrix rooms.
> chanmon.pl 2.7: Make tags configurable

- python/soju.py
Before adding a temporary server with the name used by the bouncer,
sanitize the name to make sure it doesn't include whitespace and
special characters.
> soju.py 0.1.3: sanitize network names

- python/grep_filter.py
- Script name: grep_filter.py
- Version: 0.11
Add new parameters in function hdata_search (WeeChat >= 3.4), reformat script with black.
> grep_filter.py 0.11: make script compatible with WeeChat >= 3.4

- python/soju.py
- Script name: soju.py
- Version: 0.1.4
> soju.py 0.1.4: make script compatible with WeeChat >= 3.4

- ruby/samechannel.rb
- Script name: samechannel.rb
- Version: 0.2
> samechannel.rb 0.2: make script compatible with WeeChat >= 3.4

- python/soju.py
- Script name: soju.py
- Version: 0.1.5
1. Correctly slices and dices usernames that contain `@client` suffix. `user@client` becomes `user/network@client` for the generated connections.
2. Applies the same handling to `sasl_username` parameter.
---
cc @emersion for review :)
> soju.py 0.1.5: adapt all username settings

- python/zncplayback.py
- Script name: zncplayback.py
- Version: 0.2.2
I somehow ended up with a 0 Byte SCRIPT_SAVEFILE, which made json.load()
throw an exception, which made the plugin do nothing at all. This fixes that kind of
problem.
Lint score is actually 99/100, but only because of the www.weechat.org vs weechat.org thing, which kind of doesn't belong in this PR.
> zncplayback.py 0.2.2: handle invalid json in SCRIPT_SAVEFILE

- python/soju.py
This allows multiple clients to synchronize unread statuses.
> soju.py 0.2.0: add support for soju.im/read

- python/urlgrab.py
- Script name: urlgrab.py
- Version: 3.1
This adds an option to store URLs by the full_name of the buffer, rather
than the short_name or name that is currently the default.
This fixes an issue that I had directly, where some buffers would
(frequently) get typing indicators at the short name, thus storing the
URL under `>general` instead of `#general`. This would break trying to
open URLs by index in the channel.
This should also address issue #90, as the full name should contain the
network information in it.
There is also a small linting cleanup, using `completion_list_add` and
fixing the weechat URLs
> urlgrab.py 3.1: store urls by buffer `full_name`

- python/openbsd_privdrop.py
- Script name: openbsd_privdrop.py
- Version: 0.1.0
- Requirements: OpenBSD
- Min WeeChat version: 1.3
- Script tags: py3
The `openbsd_privdrop.py` script tries to achieve the principle of least privilege for a WeeChat running on OpenBSD by restricting both the available system operations as well as the available file system paths by [pledge(2)](https://man.openbsd.org/pledge.2) and [unveil(2)](https://man.openbsd.org/unveil.2).
> New script openbsd_privdrop.py: least privilege on OpenBSD

- python/autojoin_on_invite.py
- Script name: autojoin_on_invite.py
- Version: 0.9
Fixed regex for nick parsing when the server doesn't have message tags (it was throwing an error):
11:48:22 python: stdout/stderr (autojoin_on_invite): Traceback (most recent call last):
11:48:22 python: stdout/stderr (autojoin_on_invite):   File "/home/codegeek/.local/share/weechat/python/autoload/autojoin_on_invite.py", line 94, in invite_cb
11:48:22 python: stdout/stderr (autojoin_on_invite):     from_nick = re.search(SearchStr, signal_data).groups()[0]
11:48:22 python: stdout/stderr (autojoin_on_invite): AttributeError: 'NoneType' object has no attribute 'groups'
11:48:22 =!= python: error in function "invite_cb"
> autojoin_on_invite.py 0.9: Fix nick regex

- python/read_marker.py
- Script name: read_marker
- Version: 0.1.0
- Requirements: none
- Min WeeChat version: none
- Script tags: irc, buffer
This script adds support for the draft/read-marker IRCv3 extension: https://ircv3.net/specs/extensions/read-marker
> New script read_marker.py: draft/read-marker extension support

- python/soju.py
- Script name: soju.py
- Version: 0.3.0
This IRC extension has been accepted by IRCv3 and has become draft/read-marker. The soju extension is deprecated.
Users can install [read_marker.py](https://github.com/weechat/scripts/pull/507) to get the same functionality.
> soju.py 0.3.0: remove soju.im/read support

- python/colorize_nicks.py
- Script name: colorize_nicks.py
- Version: 30
I've added ":" and "," to VALID_NICK regexp.
The point is to don't reset the colorization in input_line when you address someone by nick (like `FlashCode:` or `FlachCode,`).
> colorize_nicks.py 30: added "[:,]" to VALID_NICK

- python/openbsd_privdrop.py
- Script name: openbsd_privdrop.py
- Version: 0.1.1
> version 0.1.1: sane defaults for unveil
Prior to this change, the `unveil(2)` system call enforced a very harsh filter by default. This led, for example, to the situation that external scripts could not be installed. This change now allows this and has been tested out by me for over a month so far.
> openbsd_privdrop.py 0.1.1: sane defaults for unveil

- python/urlgrab.py
- Script name: `urlgrab.py`
- Version: 3.2
It will automatically open the URI in the default browser for the system, without having users to change it to their browser.
> urlgrab.py: Use xdg-open as default local command

- ruby/input_lock.rb
- Script name: input_lock.rb
- Version: 0.2
- Requirements: none
Refactored / simplified, and added an optional automatic idle input lock.
> input_lock.rb: 0.2: Add automatic idle lock.

- python/soju.py
- Script name:  soju.py
- Version: 0.4.0
Fix a compatibility problem with weechat 4.0.0
> soju.py 0.4.0: from ssl to tls on weechat >= 4.0.0

- python/fish.py
- Version: 0.15
- fix encoding errors with message markers (provided by @andkem)
> fish 0.15: fix encoding errors with message markers

- python/greentext.py
- Script name: greentext
- Version: v1
- Script tags: color, display, py3
Colorize imageboard-style text formatting.
Both inbound and outbound messages are colored.
Since the coloring uses IRC color codes,
outbound greentexting will be visible to both you and your friends.
The following are supported:
+ greentext
+ purpletext
+ redtext
> New script greentext.py: colorize imageboard-style text formatting

- python/autosort.py
- Script name: autosort.py
- Version: 3.10
Fixes an exception in the command `/autosort helpers swap`.
Also replaces the deprecated `hook_completion_list_add` with `completion_list_add` and fixes a false positive lint about mixed indentation.
> Update autosort.py to 3.10.

- python/slack.py
This is version 2.10.2 of slack.py (currently the most recent), copied over from the wee-slack repo.
- Version: 2.10.2
- Requirements: unchanged
- Min WeeChat version: unchanged
- Script tags: unchanged
See https://github.com/wee-slack/wee-slack/releases/tag/v2.10.2
> slack.py 2.10.2: Merge with mainline

- python/buffer_autoclose.py
- Script name: buffer_autoclose.py
- Version: 0.6
E.g. the Matrix script maps private rooms with multiple people to buffers in weechat which are nominally not private. This means that these rooms pile up, which is normally solved for real 1:1 private chats.
Fix the problem by adding a way to autoclose also non-private buffers.
No behavior is changed unless the new config option is set.
> buffer_autoclose.py 0.6: add setting to prefer closing some buffers

- lua/cmus_announce.lua
- Script name: cmus_announce.lua
- Version: 1
- Script tags: lua, music, command, audio
creates /cmus_announce command that will /me on current buffer/channel the currently playing song.
> new script lua/cmus_announce.lua: -- Announces now-playing song in cmus to current buffer/channel.

- python/twitch.py
twitch.py 1.0: eval client_id and token expressions so that /secure can be used
I'm the original script author
> twitch.py 1.0: eval client_id and token expressions so that /secure can be used

- python/beinc.py
- Script name: beinc.py
- Version: 4.4
- Min WeeChat version: 0.4.0
- Script tags: notify
Upgrades to BEINC 4.4: https://github.com/blackm0re/BEINC/releases/tag/v4.4
> beinc.py 4.4: add some minor fixes and code cleanup

- python/openbsd_privdrop.py
- Script name: `openbsd_privdrop.py`
- Version: 0.1.1 -> 0.1.2
Since WeeChat 4.3.0, the return value of `chmod` is being checked[^0]. This revealed a too strict pledge promise, missing `fattr`.
As an additional change, the level of documentation was increased, including a remainder why read permissions on /home are necessary.
[^0]: https://github.com/weechat/weechat/commit/2423fdbf2d66d241c809f797f75afd65dff91568#diff-b08b83cf9b86fa0f5c4ca579554a7ba593a892fd143526210844a05701e57058
> openbsd_privdrop.py 0.1.2: add fattr to pledge_promises

- python/slack.py
This is version 2.11.0 of slack.py (currently the most recent), copied over from the wee-slack repo.
- Version: 2.11.0
- Requirements: unchanged
- Min WeeChat version: unchanged
- Script tags: unchanged
See https://github.com/wee-slack/wee-slack/releases/tag/v2.11.0
> slack.py 2.11.0: Merge with mainline

- python/twitch.py
- Script name:  twitch.py
- Version:  1.1
- Requirements: 
- Min WeeChat version:  4.1.0
- Script tags: twitch py3
changed hook_modifier from "irc_in_WHISPER" to "irc_in2_WHISPER"
changed hook_process_hashtable("url:") to hook_url
use rawstrings to keep invalid escapes from throwing warnings
> twitch.py 1.1: multiple changes version bump
