weechat/scripts

python/undernet_totp.py
- UnderNET LoC support
- A few minor cosmetic fixes
- Updated description of the script
=> undernet_totp.py 0.3.1: add support for OTP using login on connect

python/mnotify.py
These are some fixes I made after installing the script on my machine.
I also opened this against @mmaker's repository, but I don't know if it is still maintained there (the version in here is more recent): mmaker/mnotify#3
=> Some fixes to mnotify.py

python/buffer_autoset.py
Previously buffer_autoset.py required buffers to be reopened for the set options to apply or the user had to also run an extra `/buffer set` command. This change makes the script listen to the script's config options and applies them immediately, even when modifying the settings directly not via the script's command. It does not do anything when the option gets removed because there's no way to retrieve the supposed value.
*Tested by me and strayPuppy from #weechat.*
=> buffer_autoset.py 0.9: instantly apply properties

python/autosort.py
Upper case rules caused problems with case insensitive sorting. This PR should fix it.
=> autosort 2.6: fix case insensitive sorting for rules with upper case.

python/autojoin_on_invite.py
This change makes the script use channel keys from server's `autojoin` option when joining a channel (disable-able via an option).
=> autojoin_on_invite.py 0.6: allow joining channels with keys in autojoin (closes #99)

python/autoconnect.py
Previously it was not possible to differentiate between a '/disconnect
network' command and '/quit'. When you disconnect a network you might
not want to save the channel list, but you do want that on quit.
Also restructured the code a bit since the join and part callbacks
shared much code. Now also using a set to keep track of channels and
make add remove a bit easier.
=> autoconnect.py 0.3: save channels on exit, restructure

python/lastfm.py
For more information, see:
- https://github.com/weechat/scripts/issues/97#issuecomment-172318746
- https://github.com/weechat/scripts/commit/af6f474f087ca59121c65a9eb100841c9258da10#commitcomment-15494921
Thanks.
=> lastfm.py 0.7: Fix UnicodeEncodeError

perl/buffers.pl
This new option controls what messages cause a buffer to be attached that was detached when option "detach_buffer_immediately" is enabled based on message notify level
=> buffers.pl 5.4: added option "detach_buffer_immediately_level"

python/weetweet.py
Hopefully this pull request is correct this time... :P
=> Update weetweet to version 1.2.4

python/slack.py
This brings slack.py to parity with the current code in the wee-slack repository. There are a few enhancements and quite a few bug/performance fixes.
The script name is the only bit that remains different between the repos, but we'll need to do a migration of configuration to the new name on our side.
=> slack.py 0.99.10: merge with mainline

python/autosort.py
Swapping buffers is now done with numbers instead of names. Requires more bookkeeping, but doesn't break when buffer names contain spaces.
=> autosort.py 2.7: Properly handle buffers with space in their name.

python/topicdiff.py
- Keep the order of chunks
- Move the '-'/'+' symbols into the prefix and color them red/green
- Allow '~' and '-' as chunk separators
Sample output:
=> topicdiff.py 0.3: improve diff output

python/twitch.py
Added some help information that was previous only available via github.
Can you also update the script description on weechat.org to match the one defined in the script
=> twitch.py 0.2: added detailed /help

python/gnome_screensaver_away.py
- Prevent changing manually-set away status
- Allow configuration of message and poll time
- Tolerate gnome-shell crashes
=> gnome_screensaver_away.py 0.2.0: don't trample manual away

perl/pushover.pl
Also dropped support for the other notification services in favor
of the new hsignal "pushover".
This can be used with any /trigger (for example combined with /exec)
or from other weechat scripts. That way it's very easy to use different
different notification services without having to reimplement the entire
"when to notify" logic and without bloating this script.
See /help pushover for trigger examples.
=> pushover.pl 2.0: fix pushover.net API call

python/weetweet.py
This is the patch for https://github.com/DarkDefender/weetweet/issues/12
I hope that I didn't overlook anything obvious.
=> weetweet.py 1.2.5: Add support for encrypted tokens with sec.conf

python/otr.py
Set buffer local vars with OTR conversation status.
=> otr.py 1.9.0: fix log command help and completion

python/fish.py
This substitutes the message before it ends up being sent to the buffer.
After the message with the mark is drawn in the buffer, the later `PRIVMSG` hook strips the marker back before encrypting and sending it to the network.
=> fish 0.9.2: also put mark on outgoing messages

python/irssinotifier.py
The purpose of this change is to make it possible to store the API token and the encryption key using weechat's secured data functionality, as these settings may be sensitive.
Unfortunately the Github [repo](https://github.com/leitmedium/weechat-irssinotifier) where the script origins from seems to be abandoned, so I've not been able to contact the author.
=> irssinotifier.py 0.8: add the ability to store certain potentially sensitive settings as secure data

python/twitch.py
fix for a unicode related error
=> twitch.py 0.3: fixed whois output of utf8 display names

python/spotify.py
xt was emailed when this pr was opened waiting for response
=> spotify.py 0.8: add now required oauth support

python/otr.py
Fix potr ErrorReceived printing bug.
Argument parsing errors now raise exceptions.
Fix require_encryption policy hint.
=> otr.py 1.9.1: Fix traceback caused by non-ASCII nick

python/autosort.py
This update swaps out the old sorting rules for rules using eval expressions, inspired by the new buffers plugin. Each sort rule is an eval expression, and buffers are sorted based on the value of each evaluated expression.
To aid debugging sort rules, there's a new subcommand: `/autosort debug` to show the evaluated sort rules along with timing information. 
To cope with lack of substring replacement in eval expressions, the updated script also adds an info: `${info:autosort_replace,old,new,text}`, for example to replace `##` with `#` when sorting.
The new script also adds a second info `${info:autosort_order,value,first,second,...}` to easily sort on some specific values of an expression in a specified order (`*` can be used as a placeholder for non-matching values).
The new version …
=> autosort.py 3.0: switch to eval expressions for sorting rules.

python/weetweet.py
Other changes:
More robust twitter stream reconnection code
Allow script to work on multi user machines
=> weetweet.py 1.2.7: Update for weechat 2.0.1 API changes

python/slack.py
This is version 2.0.0 of slack.py (currently the most recent), copied
https://github.com/wee-slack/wee-slack/releases/tag/v2.0.0
=> slack.py 2.0.0: Merge with mainline

python/twitch.py
Please also mark this script as py3-ok. Its been python2/3 compliant for a long time but i never bothered asking you to mark it so.
=> twitch.py: v0.5: few updates

python/latex_unicode.py
Includes
> latex_unicode.py 0.9: remove ungrouped script replacement
because apparently I never bothered to update I guess.
=> latex_unicode.py 1.0: add Python 2/3 compatibility

python/aformat.py
Tested with [weechat-python3-git](https://aur.archlinux.org/packages/weechat-python3-git/) from AUR.
=> aformat.py 0.2: make it py3k-ok

python/btc_ticker.py
btc_ticker.py 2.1.0: py3k-ok update
=> btc_ticker.py 2.1.0: py3k-ok update

python/slack.py
This is version 2.1.1 of slack.py (currently the most recent), copied
https://github.com/wee-slack/wee-slack/releases/tag/v2.1.1
=> slack.py 2.1.1: Merge with mainline

python/vimode.py
- Added support for:
- user-defined key mappings (`:nmap {lhs} {rhs}`/`:nunmap {lhs}`)
- undo history
- optional vim-like search
- command-line mode history
- various customization options (mode indicator colors and prefix/suffix; line numbers prefix/suffix)
- Removed the separate command-line bar (the input bar is now used instead).
- Other bug fixes and improvements.
=> vimode.py 0.7: several additions and fixes

python/weetweet.py
The diff is so huge because of some general code style cleanups.
However, the only real change should be that weetweet now doesn't use the depreceated twitter API anymore.
=> weetweet.py 1.2.8: Do not use the deprecated user streams anymore

python/slack.py
This is version 2.2.0 of slack.py (currently the most recent), copied
=> slack.py 2.2.0: Merge with mainline

python/screen_away.py
=> screen_away.py 0.16: add option "socket_file", for use with e.g. dtach

python/autosort.py
Changelog:
* Fix rate-limit of sorting to prevent high CPU load and lock-ups.
* Fix bug in parsing empty arguments for info hooks.
* Add debug_log option to aid with debugging.
* Correct a few typos.
=> autosort 3.4: Fix rate limiting and empty argument for info hook.

python/buffer_autohide.py
This version makes use of general buffer information and signals,
rather than IRC specific, so that buffers from other plugins can work
as well.
Improves wee-slack/wee-slack#668
=> buffer_autohide 0.5: Support buffers from plugins other than IRC

python/slack.py
This is version 2.3.0 of slack.py (currently the most recent), copied over from the wee-slack repo.
I didn't find any way to change the tags, but the script is compatible with Python 3 now, so you can set the `py3-ok` tag on it.
I see on https://weechat.org/scripts/python3/ that you sent out an e-mail to all script authors. However, since I'm not set as the script author I didn't get it. I am however the current maintainer and would like such e-mails. I see that I shouldn't change the script author, is there any other way I can receive such e-mails?
=> slack.py 2.3.0: Merge with mainline

python/autosort.py
This PR adds an info hook `${info:autosort_escape,...}` to escape commas (and backslashes) in strings, to pass them as arguments to other autosort info hooks. This is necessary for example when buffer names passed to `${info:autosort_replace,...}` contain commas or backslashes.
Changelog:
* Add ${info:autosort_escape,...} to escape arguments for other info hooks.
=> autosort.py 3.5: Add ${info:autosort_escape,...} hook.

python/autosort.py
This PR only adds documentation for info hooks provided by the `autosort.py` script. No functional changes.
Changelog:
* Add more documentation on provided info hooks.
=> autosort.py 3.6: Add more documentation on provided info hooks.

python/autobump.py
This version also is definitely Python 3 compatible (it is currently running on Python 3).
=> autobump.py 0.1.0: improve activity detection

python/latex_unicode.py
WeeChat issue: https://github.com/weechat/weechat/issues/538.
=> latex_unicode.py 1.1: fix completion newlines with workaround

python/url_hint.py
Squashed commit of the following:
commit 5ad2267db3c7c5c1d67fc9803208dd680bc0fbb3
Author: oakkitten <oakkitten@users.noreply.github.com>
Date:   Sat Aug 24 10:49:09 2019 +0300
a very minor fix
commit f8cf7eeb19419ac8775bdcc2be94e8b6618b7393
Author: oakkitten <oakkitten@users.noreply.github.com>
Date:   Fri Aug 23 11:00:57 2019 +0300
minor refactoring
commit 84678ba26b7c50162506f7263f4ee012981cc618
Author: oakkitten <oakkitten@users.noreply.github.com>
Date:   Wed Aug 21 04:08:53 2019 +0300
remove unneeded line breaks in docstring
commit 51bddf428b8c68a8fd2aee521f467ec4786aebc8
Author: oakkitten <oakkitten@users.noreply.github.com>
Date:   Wed Aug 21 03:54:57 2019 +0300
make indentation in line with weechat
commit f4851d3df88b43f896d9b8b46e8661f9985ace3b
Author: oakkitten …
=> url_hint.py 0.8: py3k-ok and and miscellaneous improvements

python/twitch.py
I updated my script to make use of a newer API as the previous has reached EOL.
This script now uses curl httpheader option which requires weechat version 2.2 or newer.
=> twitch.py 0.7: update script to use newer api

python/twitch.py
changed input modifier hooks to use irc_in2_* instead to avoid py3 unicode decoding errors
added setting 'plugins.var.python.twitch.notice_notify_block'
added setting 'plugins.var.python.twitch.client_id'
@flashcode you can bump min version again for this script up to 2.3 as i added 'weechat.hook_line' to it
=> twitch.py 0.8: updated script

python/correction_completion.py
I have added Python 3 support to correction_completion.py.
=> correction_completion.py: Python 3 support

python/away_action.py
I have added include_text option where forwarding of confidential messages is not allowed.
Also slightly re-factored command arguments formatting.
=> away-action.py 0.7: add include_text option

python/emoji_aliases.py
these two problems just came together for someone on freenode to create this:
`=!= :andril!~andril@2601:586:8400b'\xf0\x9f\x85\xb0' d6b9:a1f2:8545:a4c3 QUIT :Ping timeout: 256 seconds`
from a user with a hostmask of `:andril!~andril@2601:586:8400:a:d6b9:a1f2:8545:a4c3`
=> only parse emoji in :trailing params and fix py3 bytes vs str issue

python/slack.py
This is version 2.4.0 of slack.py (currently the most recent), copied
=> slack.py 2.4.0: Merge with mainline

python/slack.py
This is version 2.5.0 of slack.py (currently the most recent), copied
=> slack.py 2.5.0: Merge with mainline

python/slack.py
This is version 2.6.0 of slack.py (currently the most recent), copied
=> slack.py 2.6.0: Merge with mainline

python/twitch.py
Added support for oauth token which is now required by twitch API for queries.
Fixed bug when API returns null data for game_id - thanks to mas90 for PR
=> twitch.py 0.9: add support for oauth tokens

python/bandwidth.py
Added python3 support while still supporting python2
=> bandwidth.py 1.1: add support of python3

python/arespond.py
not original script author they appear to be inactive.
added py3 support while keeping py2 support
fixed issue with command not being executed in the right buffer
renamed option 'muted' to 'enabled' so its more intuitive
after merge please add py3 flag on weechat.org repo and leave py2 flag intact
=> arespond.py 0.1.1: added py3 support

python/leet.py
Added support of python3 while retaining support of python2
script is now py3-ok and py2-ok
=> leet.py 0.2: Added support of python3 while retaining support of python2

python/slack.py
This is version 2.7.0 of slack.py (currently the most recent), copied
=> slack.py 2.7.0: Merge with mainline

python/lossage.py
- Script name: lossage
- Version: 0.1
- Min WeeChat version: 1.0
- Script tags: py3, input
Inspired by Emacs's view-lossage, this script displays a history of the last keystrokes you performed and the commands invoked.
=> New script lossage.py: displays the last few input keystrokes and the commands run

python/notification_center.py
- Script name: `notification_center.py`
- Version: 1.5.2
Version 1.5.2 of `notification_center` uses `weechat_config_dir`/`weechat_dir`
to find the path to the Weechat icon rather than hardcoding `~/.weechat`.
=> notification_center 1.5.2: use weechat_config_dir to find icon

python/weenotifier.py
- Script name: weenotifier.py
- Version: 0.0.1
- Requirements: cryptograpy
- Script tags: IrssiNotifier, push, notify
notifier which is capable of communicating with IrssiNotifier(https://irssinotifier.appspot.com/).  This IrssiNotifier  uses to deliver notifications. This can be a great supplement for weechat-android.
=> weenotifier.py: notifier using IrssiNotifier

python/fish.py
The underlying C code performing the blowfish encryption wants bytes and
not a python string. Encode as utf-8 to avoid the issue below.
```
Traceback (most recent call last):
File "/home/andkem/.weechat/python/autoload/fish.py", line 861, in fish_modifier_in_privmsg_cb
b = Blowfish(fish_keys[targetl])
File "/home/andkem/.weechat/python/autoload/fish.py", line 379, in __init__
self.blowfish = Crypto.Cipher.Blowfish.new(
File "/usr/lib/python3.9/site-packages/Crypto/Cipher/Blowfish.py", line 146, in new
return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
File "/usr/lib/python3.9/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
return modes[mode](factory, **kwargs)
File "/usr/lib/python3.9/site-packages/Crypto/Cipher/_mode_ecb.py", line 215, in …
```
=> fish.py 0.9.7: utf-8 encode key passed to blowfish

python/buffer_open.py
- Script name: buffer_open.py
- Version: 0.3
=> buffer_open.py 0.3: make script compatible with WeeChat >= 3.4

python/collapse_channel.py
- Script name: collapse_channel.py
- Version: 0.9
=> collapse_channel.py 0.9: make script compatible with WeeChat >= 3.4

perl/stalker.pl
- Script name: stalker.pl
- Version: 1.6.3
=> stalker.pl 1.6.3: make script compatible with WeeChat >= 3.4

python/autoauth.py
- Script name: autoauth.py
- Version: 1.3
Add new parameters in function hdata_search (WeeChat >= 3.4), reformat script with black.
=> autoauth.py 1.3: make script compatible with WeeChat >= 3.4

python/cmdqueue.py
- Script name: cmdqueue.py
- Version: 0.4.5
Fix inconsistent tabs/spaces in cmdqueue.py and improve formatting
This was done in Visual Studio Code, with the Python extension and autopep8.
I chose not to include formatting where it would split functions onto separate lines but kept all other suggestions.
=> cmdqueue.py 0.4.5: Fix spacing and improve formatting

python/reop.py
- Script name: reop
- Version: 1.0.0
- Requirements: none
- Min WeeChat version: 2.3
- Script tags: irc mode py3
Unlike most automatic op/voice plugins, this plugin uses the reop (R) and invite (I) lists of a channel for automatic op and voice control. This allows for transparent and centralised channel administration while responsibility is shared with all channel operators. This is particularly useful for networks that have no services (e.g., IRCnet).
=> New script reop.py: Automatically op/voice users using reop and invite lists.

python/fish.py
- Version: 0.11
- Requirements: pycryptodome
=> fish.py 0.11: support decryption of messages in CBC mode

python/upside_down.py
- Script name: upside_down.py
- Version: 0.3.1
=> Port upside down.py to python3

python/fish.py
- Version: 0.12
fix decryption of truncated messages in CBC mode
closes #500
=> fish.py 0.12: fix decryption of truncated messages in CBC mode

python/autojoin_on_invite.py
to account for CAPS/time feature on newer ircds (@time=2022-03-02T19:00:30.041Z :XXXX!~XXXX@xxxx INVITE yournick :#xxxxxxxx)
- Script name: autojoin_on_invite.py
- Version: 0.8
updated regex
=> autojoin_on_invite.py 0.8: slight regex tweak

python/colorize_nicks.py
- Script name: colorize_nicks.py
- Version: 29
The first change is so that nicknames are checked for min_nick_length or blacklist *after* stripping e.g. the ":" address part.
The second change is so that I can see my good friend `k` in colour.
=> colorize_nicks.py 29: check nick for exclusion *after* stripping, decrease minimum length to 1

python/beinc.py
- Script name: 
- Version: 4.3
- Script tags: notify py3
Remove obsolete SSL/TLS code and re-style the code
=> beinc.py 4.3: remove obsolete SSL/TLS code and re-style code

python/slack.py
This is version 2.9.0 of slack.py (currently the most recent), copied over from the wee-slack repo.
Note that the Slack API will introduce a breaking change tomorrow (2022-09-20) which means that all earlier versions of slack.py will stop working. This release supports the change and will not be affected.
- Version: 2.9.0
- Requirements: python websocket-client
- Min WeeChat version: 1.3
- Script tags: slack, py2, py3
The new version is updated to still work after a breaking change in the Slack API on September 20, 2022. It also adds support for the new type of session tokens and fixes some bugs.
- It complains about usage of two deprecated API methods (`hook_completion_get_string` and `hook_completion_list_add`), but it complains even if it's in a condition, so …
=> slack.py 2.9.0: Merge with mainline

python/fish.py
- Version: 0.13
handle message tags from ircv3
=> fish.py 0.13: handle message tags from ircv3

python/slack.py
This is version 2.9.1 of slack.py (currently the most recent), copied over from the wee-slack repo.
Note that I updated the script author, as discussed on IRC.
- Version: 2.9.1
- Requirements: websocket-client
- Min WeeChat version: 2.2
- Script tags: slack, py2, py3
Bug fixes, see https://github.com/wee-slack/wee-slack/releases/tag/v2.9.1 for the full list. Also removed usage of deprecated WeeChat API methods.
=> slack.py 2.9.1: Merge with mainline

python/wee_most.py
- Script name: wee_most
- Version: 0.2.0
- Requirements: [websocket-client](https://github.com/websocket-client/websocket-client)
Integration with Mattermost servers
Project page: https://sr.ht/~tardypad/wee-most/
=> New script wee_most.py: Mattermost integration

python/fish.py
- Version: 0.14
- Requirements: pycryptodome
- Improve Pycryptodome dependency; also try to import from `Cryptodome` aditionally to `Crypto`.
- Fix a `TypeError` when `fish_secure_key` is set.
=> fish.py 0.14: fix TypeError, improve dependency

python/sarcasm.py
- Script name: Sarcasm.py
- Version: 1.0
- Requirements:
- Script tags: display py3
Adds random capitalization to text to indicate sArCAsm
=> New script sarcasm.py: Adds random capitalization

perl/multiline.pl
- Script name: multiline.pl
- Version: 0.6.4
- Requirements: `Pod::Parser` if using perl >= 5.32.0 (existing requirement, not new in this PR)
Uses the new key names for WeeChat >= 4.0.0 and the old key names for older versions. For ctrl-m and ctrl-j it still uses these names rather than the new return name, because it handles ctrl-m and ctrl-j differently (but uses the correct version of it, e.g. ctrl-m for new versions and ctrl-M for old versions, so it works in all versions).
- I've mentioned that I'm doing it at least
=> multiline.pl 0.6.4: support new key names in WeeChat 4.0.0

python/wee_most.py
- Script name: wee_most.py
- Version: 0.3.0
- Add suffix to successfully downloaded files See look.file_downloaded_suffix and color.file_downloaded_suffix configuration options
- Fix handling of user_added WebSocket event in case of non existing channel
- Fix handling of user_removed WebSocket event
- Fix display of polls
- Delete input line before inserting reply/react/unreact command
- Use channel last_viewed_at property to determine if post is read or not
- Strip leading and trailing newlines from post display
=> wee_most.py 0.3.0: new release

python/soju.py
Instead of overwriting the irc.server_default.capabilities config option, use the new irc_cap_sync_req modifier to request the extra bouncer-networks capability.
=> soju.py 0.5.0: use irc_cap_sync_req modifier

python/read_marker.py
Instead of overwriting the irc.server_default.capabilities config option, use the new irc_cap_sync_req modifier to request the extra read-marker capability.
=> read_marker.py 0.2.0: use irc_cap_sync_req modifier

python/slack.py
This is version 2.10.0 of slack.py (currently the most recent), copied over from the wee-slack repo.
- Version: 2.10.0
- Requirements: python websocket-client
- Min WeeChat version: 2.2
- Script tags: slack, py2, py3
See https://github.com/wee-slack/wee-slack/releases/tag/v2.10.0
=> slack.py 2.10.0: Merge with mainline

python/slack.py
This is version 2.10.1 of slack.py (currently the most recent), copied over from the wee-slack repo.
- Version: 2.10.1
- Requirements: same as previous version 
- Min WeeChat version: same as previous version
- Script tags: same as previous version
See https://github.com/wee-slack/wee-slack/releases/tag/v2.10.1
=> slack.py 2.10.1: Merge with mainline

python/emojize.py
- Script name: emojize.py
- Version: 1.0.1
- Requirements: emoji (python package)
- Min WeeChat version: 1.3
=> emojize.py 1.0.1: Fix to work with modern versions of `emoji` package
